### ISSUE TITLE
brew several commits behind Linuxbrew/brew makes homebrew-cadfael crashing in MacOS High Sierra

### ISSUE THREAD

**Issue by matteoceschia** [SuperNEMO-DBD/brew-deprecated#12]
I am a novice (just joined SN) and I was trying to install SuperNEMO software via homebrew-cadfael with some difficulties. I managed to successfully install it but maybe explaining the issues found can avoid future potential issues.

First, XCode10 seems to cause some problems: it is not recognized (gets mistaken for XCode1 raising:
Error: Your Xcode (1) is too outdated).
No problems with XCode9.2.

Second, it seems that SuperNEMO-DBD/brew is quite some commits behind Linuxbrew/brew and this caused some problems (mainly raised:
Error: undefined method `sdk_path_if_needed' for OS::Mac:Module).
There are some minimal changes in a couple of .rb files which can be done and worked for me. I am including those in a pull request if a full update is not the preferred choice.

Hope this might be useful!

# Please always follow these steps:
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new. If it's a tap problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor`

**Comment by matteoceschia** [comment]
pull request mentioned #13

**Comment by drbenmorgan** [comment]
@matteoceschia, based on some recent testing, I'm now recommending that users migrate to using the official Linuxbrew (or Homebrew). To do this on High Sierra with Xcode 10 (NB Mojave is *not* tested yet), do:

```console
$ git clone https://github.com/Linuxbrew/brew.git
$ export PATH=$(pwd)/brew/bin:$PATH
$ brew doctor
... assuming o.k. ...
$ brew tap supernemo-dbd/cadfael
$ brew tap-pin supernemo-dbd/cadfael
$ brew install falaise
```

If that doesn't work, please submit an Issue on supernemo-dbd/homebrew-cadfael.
