### ISSUE TITLE
Installation @CCAGE and readline issue

### ISSUE THREAD

**Issue by lemiere** [SuperNEMO-DBD/brew-deprecated#3]
After a brew install bayeux, I got : 
==> Installing dependencies for supernemo-dbd/cadfael/bayeux: readline, icu4c, supernemo-dbd/cadfael/boost, supernemo-dbd/cadfael/camp, supernemo-dbd/cadfael/clhep, supernemo-dbd/cadfael/xerces-c, supernemo-dbd/cadfael/geant4, sqlite, supernemo-dbd/cadfael/root6, libpng, freetype, expat, fontconfig, supernemo-dbd/cadfael/qt5-base
==> Installing supernemo-dbd/cadfael/bayeux dependency: readline
==> Downloading https://ftp.gnu.org/gnu/readline/readline-7.0.tar.gz
Trying a mirror...
==> Downloading https://ftpmirror.gnu.org/readline/readline-7.0.tar.gz
Error: Failed to download resource "readline"
Download failed: https://ftpmirror.gnu.org/readline/readline-7.0.tar.gz

Have you any idea ? 
Regards,
Yves

**Comment by drbenmorgan** [comment]
Hi @lemiere, both of those links are working for me, so I would suspect a network issue. Are you able to download these directly, e.g.

```
$ curl -O https://ftp.gnu.org/gnu/readline/readline-7.0.tar.gz
... or ...
$ curl -O https://ftpmirror.gnu.org/readline/readline-7.0.tar.gz
```

If those don't work at least it should give some indication of the problem. If they do work, try 

```
$ brew install -v readline
```

as that should give more information, including progress of the download.

**Comment by lemiere** [comment]
Note that : I'm connected via qlogin to use interactive batch to install sw.
I tried using wget and it worked!
I tried to declare HOMEBREW_TEMP and put tarball on that dir but failed....
It's also the case for icu4c, libpng....

Note that : On another worker (not interactive batch using qlogin), it worked!

**Comment by drbenmorgan** [comment]
Closing issues older than 2 months.
